version: '3'
services:
  grpc-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    environment:
      - "GRPC_PORT=5000"
  grpc-gateway:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gateway
    ports:
      - "3000:3000"
    environment:
      - "GATEWAY_TARGET=grpc-server:5000"
      - "GATEWAY_PORT=3000"
