version: '2'
services:
  grpc-server:
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      - APP_PORT=5000
  grpc-gateway:
    build:
      context: .
    command:  /usr/local/bin/gateway
    ports:
      - 3000:3000
    environment:
      - TARGET_PORT=5000
      - APP_PORT=3000
