#!/usr/bin/env bash

set -eu
set -o pipefail

OS=osx # When linux, set `linux`
DEPENDENCIES=("go direnv")

PROTOC_VERSION=3.3.0
PROTOC_ZIP=protoc-${PROTOC_VERSION}-${OS}-x86_64.zip


check() {
  errcount=0
  for d in ${DEPENDENCIES[@]}; do
    if ! ( test $(which ${d}) )
    then
      echo "Please install ${d}"
      (( errcount++ ))
    fi
  done
  if [ $errcount -gt 0 ]; then
    exit 1
  fi
}

setup() {
  [ -f .env ] || cp .env{.sample,}
  direnv allow
}

setup_protoc() {
  curl -OL https://github.com/google/protobuf/releases/download/v3.3.0/${PROTOC_ZIP}
  sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
  rm -f $PROTOC_ZIP

  go get -u -v github.com/golang/protobuf/protoc-gen-go
  go get -u -v google.golang.org/grpc
}

main() {
  check
  setup
  setup_protoc
}

main
