// Code generated by protoc-gen-go. DO NOT EDIT.
// source: recommend.proto

package com_github_rerost_python_with_grpc_gateway

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Score                float64           `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	ScoreDescription     *ScoreDescription `protobuf:"bytes,3,opt,name=score_description,json=scoreDescription,proto3" json:"score_description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_b22f281c2bb00329, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetScore() float64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *User) GetScoreDescription() *ScoreDescription {
	if m != nil {
		return m.ScoreDescription
	}
	return nil
}

type ListUsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b22f281c2bb00329, []int{1}
}

func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(m, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type Blog struct {
	Id                   int64             `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Score                float64           `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	ScoreDescription     *ScoreDescription `protobuf:"bytes,3,opt,name=score_description,json=scoreDescription,proto3" json:"score_description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Blog) Reset()         { *m = Blog{} }
func (m *Blog) String() string { return proto.CompactTextString(m) }
func (*Blog) ProtoMessage()    {}
func (*Blog) Descriptor() ([]byte, []int) {
	return fileDescriptor_b22f281c2bb00329, []int{2}
}

func (m *Blog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blog.Unmarshal(m, b)
}
func (m *Blog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blog.Marshal(b, m, deterministic)
}
func (m *Blog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blog.Merge(m, src)
}
func (m *Blog) XXX_Size() int {
	return xxx_messageInfo_Blog.Size(m)
}
func (m *Blog) XXX_DiscardUnknown() {
	xxx_messageInfo_Blog.DiscardUnknown(m)
}

var xxx_messageInfo_Blog proto.InternalMessageInfo

func (m *Blog) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Blog) GetScore() float64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Blog) GetScoreDescription() *ScoreDescription {
	if m != nil {
		return m.ScoreDescription
	}
	return nil
}

type ListBlogsResponse struct {
	Blogs                []*Blog  `protobuf:"bytes,1,rep,name=blogs,proto3" json:"blogs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBlogsResponse) Reset()         { *m = ListBlogsResponse{} }
func (m *ListBlogsResponse) String() string { return proto.CompactTextString(m) }
func (*ListBlogsResponse) ProtoMessage()    {}
func (*ListBlogsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b22f281c2bb00329, []int{3}
}

func (m *ListBlogsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBlogsResponse.Unmarshal(m, b)
}
func (m *ListBlogsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBlogsResponse.Marshal(b, m, deterministic)
}
func (m *ListBlogsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBlogsResponse.Merge(m, src)
}
func (m *ListBlogsResponse) XXX_Size() int {
	return xxx_messageInfo_ListBlogsResponse.Size(m)
}
func (m *ListBlogsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBlogsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBlogsResponse proto.InternalMessageInfo

func (m *ListBlogsResponse) GetBlogs() []*Blog {
	if m != nil {
		return m.Blogs
	}
	return nil
}

type Score struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Score                float64  `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	ScoreFunc            string   `protobuf:"bytes,3,opt,name=score_func,json=scoreFunc,proto3" json:"score_func,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Score) Reset()         { *m = Score{} }
func (m *Score) String() string { return proto.CompactTextString(m) }
func (*Score) ProtoMessage()    {}
func (*Score) Descriptor() ([]byte, []int) {
	return fileDescriptor_b22f281c2bb00329, []int{4}
}

func (m *Score) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Score.Unmarshal(m, b)
}
func (m *Score) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Score.Marshal(b, m, deterministic)
}
func (m *Score) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Score.Merge(m, src)
}
func (m *Score) XXX_Size() int {
	return xxx_messageInfo_Score.Size(m)
}
func (m *Score) XXX_DiscardUnknown() {
	xxx_messageInfo_Score.DiscardUnknown(m)
}

var xxx_messageInfo_Score proto.InternalMessageInfo

func (m *Score) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Score) GetScore() float64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Score) GetScoreFunc() string {
	if m != nil {
		return m.ScoreFunc
	}
	return ""
}

type ScoreDescription struct {
	Scores               []*Score `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	ScoreFunc            string   `protobuf:"bytes,2,opt,name=score_func,json=scoreFunc,proto3" json:"score_func,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScoreDescription) Reset()         { *m = ScoreDescription{} }
func (m *ScoreDescription) String() string { return proto.CompactTextString(m) }
func (*ScoreDescription) ProtoMessage()    {}
func (*ScoreDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_b22f281c2bb00329, []int{5}
}

func (m *ScoreDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScoreDescription.Unmarshal(m, b)
}
func (m *ScoreDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScoreDescription.Marshal(b, m, deterministic)
}
func (m *ScoreDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScoreDescription.Merge(m, src)
}
func (m *ScoreDescription) XXX_Size() int {
	return xxx_messageInfo_ScoreDescription.Size(m)
}
func (m *ScoreDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_ScoreDescription.DiscardUnknown(m)
}

var xxx_messageInfo_ScoreDescription proto.InternalMessageInfo

func (m *ScoreDescription) GetScores() []*Score {
	if m != nil {
		return m.Scores
	}
	return nil
}

func (m *ScoreDescription) GetScoreFunc() string {
	if m != nil {
		return m.ScoreFunc
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "com.github.rerost.python_with_grpc_gateway.User")
	proto.RegisterType((*ListUsersResponse)(nil), "com.github.rerost.python_with_grpc_gateway.ListUsersResponse")
	proto.RegisterType((*Blog)(nil), "com.github.rerost.python_with_grpc_gateway.Blog")
	proto.RegisterType((*ListBlogsResponse)(nil), "com.github.rerost.python_with_grpc_gateway.ListBlogsResponse")
	proto.RegisterType((*Score)(nil), "com.github.rerost.python_with_grpc_gateway.Score")
	proto.RegisterType((*ScoreDescription)(nil), "com.github.rerost.python_with_grpc_gateway.ScoreDescription")
}

func init() { proto.RegisterFile("recommend.proto", fileDescriptor_b22f281c2bb00329) }

var fileDescriptor_b22f281c2bb00329 = []byte{
	// 410 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x93, 0x3d, 0x8b, 0xdb, 0x30,
	0x1c, 0xc6, 0x91, 0xf3, 0x42, 0xad, 0x40, 0x9a, 0x88, 0x52, 0x4c, 0xda, 0x82, 0xf1, 0x64, 0x3a,
	0xc8, 0x6d, 0xba, 0xb6, 0x4b, 0x69, 0x03, 0x85, 0x0e, 0x45, 0xa1, 0x53, 0x07, 0x63, 0xcb, 0x8a,
	0x23, 0x88, 0x25, 0x23, 0xc9, 0x0d, 0x81, 0x4e, 0xfd, 0x0a, 0x1d, 0xfa, 0xc1, 0xfa, 0x15, 0xfa,
	0x29, 0x3a, 0x15, 0xc9, 0xf1, 0xdd, 0xc5, 0xc7, 0xc1, 0xe5, 0xb8, 0xe1, 0x36, 0xe9, 0xaf, 0xe8,
	0x79, 0x9e, 0x5f, 0xf4, 0x18, 0x3e, 0x56, 0x8c, 0xca, 0xaa, 0x62, 0xa2, 0xc0, 0xb5, 0x92, 0x46,
	0xa2, 0x97, 0x54, 0x56, 0xb8, 0xe4, 0x66, 0xdb, 0xe4, 0x58, 0x31, 0x25, 0xb5, 0xc1, 0xf5, 0xc1,
	0x6c, 0xa5, 0x48, 0xf7, 0xdc, 0x6c, 0xd3, 0x52, 0xd5, 0x34, 0x2d, 0x33, 0xc3, 0xf6, 0xd9, 0x61,
	0xf1, 0xbc, 0x94, 0xb2, 0xdc, 0xb1, 0x24, 0xab, 0x79, 0x92, 0x09, 0x21, 0x4d, 0x66, 0xb8, 0x14,
	0xba, 0x55, 0x5a, 0x3c, 0x3b, 0x9e, 0xba, 0x5d, 0xde, 0x6c, 0x12, 0x56, 0xd5, 0xe6, 0xd0, 0x1e,
	0x46, 0xbf, 0x01, 0x1c, 0x7e, 0xd5, 0x4c, 0xa1, 0x29, 0xf4, 0x78, 0x11, 0x80, 0x10, 0xc4, 0x03,
	0xe2, 0xf1, 0x02, 0x3d, 0x81, 0x23, 0x4d, 0xa5, 0x62, 0x81, 0x17, 0x82, 0x18, 0x90, 0x76, 0x83,
	0x38, 0x9c, 0xbb, 0x45, 0x5a, 0x30, 0x4d, 0x15, 0xaf, 0xad, 0x4f, 0x30, 0x08, 0x41, 0x3c, 0x59,
	0xbe, 0xc5, 0xb7, 0x4f, 0x8c, 0xd7, 0x56, 0xe4, 0xc3, 0xa5, 0x06, 0x99, 0xe9, 0xde, 0x24, 0xfa,
	0x06, 0xe7, 0x9f, 0xb9, 0x36, 0x36, 0x9c, 0x26, 0x4c, 0xd7, 0x52, 0x68, 0x86, 0x56, 0x70, 0xd4,
	0xd8, 0x41, 0x00, 0xc2, 0x41, 0x3c, 0x59, 0xbe, 0x3a, 0xc7, 0xd3, 0x2a, 0x91, 0xf6, 0xba, 0xc3,
	0x7e, 0xbf, 0x93, 0xe5, 0x83, 0xc5, 0xb6, 0xe1, 0x4e, 0xb0, 0x73, 0x3b, 0xb8, 0x0b, 0xb6, 0x55,
	0x22, 0xed, 0xf5, 0xe8, 0x0b, 0x1c, 0xb9, 0x08, 0x08, 0xc1, 0xa1, 0xc8, 0x2a, 0xe6, 0xc0, 0x7d,
	0xe2, 0xd6, 0x37, 0xa0, 0xbf, 0x80, 0xb0, 0x45, 0xdf, 0x34, 0x82, 0x3a, 0x66, 0x9f, 0xf8, 0x6e,
	0xb2, 0x6a, 0x04, 0x8d, 0x7e, 0xc0, 0x59, 0x1f, 0x0a, 0x7d, 0x82, 0x63, 0xf7, 0x83, 0x2e, 0xee,
	0xeb, 0xb3, 0xff, 0x22, 0x72, 0x14, 0xe8, 0xb9, 0x7b, 0x3d, 0xf7, 0xe5, 0x3f, 0x00, 0x67, 0xa4,
	0xfb, 0x70, 0xd6, 0x4c, 0x7d, 0xe7, 0x94, 0x21, 0x05, 0xfd, 0x8b, 0xe2, 0xa0, 0xa7, 0xb8, 0x6d,
	0x3f, 0xee, 0xda, 0x8f, 0x3f, 0xda, 0xf6, 0x2f, 0xde, 0x9d, 0x93, 0xe9, 0x5a, 0x0f, 0xa3, 0xe9,
	0xcf, 0x3f, 0x7f, 0x7f, 0x79, 0x8f, 0xd0, 0x38, 0x71, 0x7d, 0xea, 0x3c, 0xdd, 0xab, 0xdd, 0x9f,
	0xe7, 0x49, 0x09, 0xae, 0x78, 0xba, 0xc7, 0xcc, 0xc7, 0x4e, 0xfe, 0xcd, 0xff, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x86, 0xd6, 0x80, 0xb2, 0x3b, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RecommendServiceClient is the client API for RecommendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecommendServiceClient interface {
	ListUsers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListUsersResponse, error)
	ListBlogs(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListBlogsResponse, error)
}

type recommendServiceClient struct {
	cc *grpc.ClientConn
}

func NewRecommendServiceClient(cc *grpc.ClientConn) RecommendServiceClient {
	return &recommendServiceClient{cc}
}

func (c *recommendServiceClient) ListUsers(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/com.github.rerost.python_with_grpc_gateway.RecommendService/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recommendServiceClient) ListBlogs(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ListBlogsResponse, error) {
	out := new(ListBlogsResponse)
	err := c.cc.Invoke(ctx, "/com.github.rerost.python_with_grpc_gateway.RecommendService/ListBlogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecommendServiceServer is the server API for RecommendService service.
type RecommendServiceServer interface {
	ListUsers(context.Context, *empty.Empty) (*ListUsersResponse, error)
	ListBlogs(context.Context, *empty.Empty) (*ListBlogsResponse, error)
}

// UnimplementedRecommendServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRecommendServiceServer struct {
}

func (*UnimplementedRecommendServiceServer) ListUsers(ctx context.Context, req *empty.Empty) (*ListUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (*UnimplementedRecommendServiceServer) ListBlogs(ctx context.Context, req *empty.Empty) (*ListBlogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBlogs not implemented")
}

func RegisterRecommendServiceServer(s *grpc.Server, srv RecommendServiceServer) {
	s.RegisterService(&_RecommendService_serviceDesc, srv)
}

func _RecommendService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.rerost.python_with_grpc_gateway.RecommendService/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendServiceServer).ListUsers(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecommendService_ListBlogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendServiceServer).ListBlogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.rerost.python_with_grpc_gateway.RecommendService/ListBlogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendServiceServer).ListBlogs(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _RecommendService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.github.rerost.python_with_grpc_gateway.RecommendService",
	HandlerType: (*RecommendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUsers",
			Handler:    _RecommendService_ListUsers_Handler,
		},
		{
			MethodName: "ListBlogs",
			Handler:    _RecommendService_ListBlogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recommend.proto",
}
